verifyDepsBeforeRun: error
runtimeOnFail: error
pmOnFail: error

packages:
  - demo

allowBuilds:
  esbuild: true
  lefthook: true
  workerd: true

minimumReleaseAgeExclude:
  - '@devlsh/tools@1.0.1'
